## 2. LIMPIEZA Y TRANSFORMACIÓN

- normalización 
- cambio del tipo dato (fecha)
- eliminar columnas 
- crear nuevas variables

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("data.csv", sep=";", engine="python", skiprows=3)

df.head()

,Campaign ID,Campaign Name,Name from,Email from,Sending date,Subject,Sent,Non delivered,Hard bounces,Soft bounces,Non delivered rate,Delivered,Total opens,Opens,Trackable open rate,Apple MPP Opens,Total clicked,Clicked,Click rate,Click-to-Open rate,Unsubscribed,Unsubscription rate,Delivered rate,Hard Bounces rate,Soft Bounces rate,Complaints,Complaints rate
0,5,Resumen Webinar enGira!,enGira!,info@engira.art,04-12-2024,Resumen Webinar enGira!,103,0,0,0,0%,103,247,87,"84,47%",19,34,19,"18,45%","27,94%",0,0%,100%,0%,0%,0,0%
1,6,Artistas Catálogo,enGira!,info@engira.art,23-10-2024,Participación Piloto enGira!,3,0,0,0,0%,3,13,3,100%,0,3,1,"33,33%","33,33%",0,0%,100%,0%,0%,0,0%
2,8,Artistas seleccionados,enGira!,info@engira.art,29-10-2024,Artistas seleccionados,38,2,0,2,"5,26%",36,773,44,100%,9,99,32,"88,89%","91,43%",0,0%,"94,74%",0%,"5,26%",0,0%
3,10,ARTISTAS TOOLKIT,enGira!,info@engira.art,28-10-2024,Participación Piloto enGira​!,122,5,2,3,"4,10%",117,974,134,100%,33,199,70,"59,83%","69,31%",0,0%,"95,90%","1,64%","2,46%",1,"0,82%"
4,12,Recordatorio,enGira!,info@engira.art,29-10-2024,Participación Piloto enGira!,24,1,0,1,"4,17%",23,214,27,100%,5,25,12,"52,17%","54,55%",0,0%,"95,83%",0%,"4,17%",0,0%

In [3]:
df = df.drop(columns=[
    "Name from", "Email from", "Hard bounces", 
    "Soft bounces", "Non delivered", "Delivered", 
    "Unsubscribed", "Complaints"])

In [4]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_")

In [5]:
df['sending_date'] = pd.to_datetime(df["sending_date"], dayfirst=True, errors="coerce")

In [6]:
df['sending_date'].dtype

dtype('<M8[us]')

In [7]:
df['year'] = df['sending_date'].dt.year
df['month'] = df['sending_date'].dt.month
df['day'] = df['sending_date'].dt.day
df['weekday'] = df['sending_date'].dt.weekday

In [8]:
df['subject'].value_counts()

subject
Nuevas convocatorias                                            7
Programa Piloto enGira!                                         4
Demo enGira!                                                    4
Participación Piloto enGira!                                    2
Fin del Programa Piloto enGira!​                                2
Descubre nuevos artistas escénicos                              2
Presentes en dFeria                                             2
Presentamos enGira! en Madferia                                 2
Resumen Webinar enGira!                                         1
Artistas seleccionados                                          1
Participación Piloto enGira​!                                   1
Jornadas enGira!                                                1
No te pierdas estas Convocatorias!                              1
Webinar enGira! 3 de diciembre                                  1
Jornadas de Internacionalización y Movilidad de Artistas!       1
Artista destacado                                               1
Jornadas de Internacionalización y Movilidad de artistas        1
Invitación Piloto enGira!                                       1
Recordatorio Webinar enGira!                                    1
Nuevas Convocatorias!                                           1
Convocatorias abiertas                                          1
Descubre artistas y conecta con ellos                           1
Descubre nuevos artistas escénicos de creación contemporánea    1
Descobreix nous artistes escènics de creació contemporània      1
Nuevas convocatorias y una "demo"                               1
Te ayudamos a completar el registro?                            1
Échale un vistazo a estas convocatorias                         1
¡Gracias por acompañarnos en la presentación de enGira!         1
enGira! | MERCARTES 2025                                        1
enGira! | Terminar registro                                     1
enGira! | ¡Nos vemos en MERCARTES 2025!                         1
enGira! - Stand 241 de MERCARTES                                1
Nuevas Convocatorias y Programas de Acompañamiento              1
Invitación al Webinar enGira!                                   1
Grabación Webinar y Plan de Acompañamiento                      1
Últimas convocatorias del año                                   1
Nuevo año, nuevas convocatorias                                 1
Name: count, dtype: int64

In [9]:
df['subject'] = df['subject'].str.lower().str.strip()

In [10]:
def clasificar_campaña(nombre):
    
    if "convocatorias" in nombre:
        return "convocatorias"
    
    elif "jornadas" in nombre:
        return "jornadas"
    
    elif "demo" in nombre or 'webinar' in nombre or 'registro' in nombre:
        return "formacion"
    
    elif "dferia" in nombre or 'madferia' in nombre or 'mercartes' in nombre:
        return "ferias"
    
    elif "descubre" in nombre or "descobreix" in nombre or 'funcionamiento' in nombre or 'piloto' in nombre or 'destacados' in nombre:
        return "promocion"
    
    else:
        return "otros"

In [11]:
df['tipo_campaña'] = df['subject'].apply(clasificar_campaña)

In [12]:
df['tipo_campaña'].value_counts()

tipo_campaña
promocion        15
convocatorias    15
formacion        11
ferias            7
otros             3
jornadas          3
Name: count, dtype: int64

In [13]:
df['campaign_name'] = df['campaign_name'].str.lower().str.strip()

In [14]:
def clasificar_publico(nombre):
    
    if 'artistas' in nombre or 'convocatorias' in nombre or 'webinar' in nombre or 'diagnostico'in nombre:
        
        return 'artistas'
    
    elif 'programadores' in nombre or 'demo' in nombre:
        
        return 'programadores'
    
    else:
        return 'all'

In [15]:
df['tipo_publico'] = df['campaign_name'].apply(clasificar_publico)

In [16]:
df['tipo_publico'].value_counts()

tipo_publico
artistas         27
programadores    16
all              11
Name: count, dtype: int64

In [17]:
df.columns

Index(['campaign_id', 'campaign_name', 'sending_date', 'subject', 'sent',
       'non_delivered_rate', 'total_opens', 'opens', 'trackable_open_rate',
       'apple_mpp_opens', 'total_clicked', 'clicked', 'click_rate',
       'click_to_open_rate', 'unsubscription_rate', 'delivered_rate',
       'hard_bounces_rate', 'soft_bounces_rate', 'complaints_rate', 'year',
       'month', 'day', 'weekday', 'tipo_campaña', 'tipo_publico'],
      dtype='str')

In [18]:
df.sample(5)

,campaign_id,campaign_name,sending_date,subject,sent,non_delivered_rate,total_opens,opens,trackable_open_rate,apple_mpp_opens,total_clicked,clicked,click_rate,click_to_open_rate,unsubscription_rate,delivered_rate,hard_bounces_rate,soft_bounces_rate,complaints_rate,year,month,day,weekday,tipo_campaña,tipo_publico
8,20,invitación piloto programadores cataluña,2024-11-06,programa piloto engira!,189,"17,46%",112,50,"32,05%",12,13,8,"5,13%","21,05%","1,92%","82,54%","3,17%","14,29%",0%,2024,11,6,2,promocion,programadores
27,70,demo programadores madrid y engira,2025-02-17,demo engira!,90,"4,44%",19,13,"15,12%",4,0,0,0%,0%,0%,"95,56%",0%,"4,44%",0%,2025,2,17,0,formacion,programadores
26,69,convocatorias + demo - 4º envío,2025-02-10,"nuevas convocatorias y una ""demo""",153,"0,65%",535,162,100%,36,199,62,"40,79%","49,21%",0%,"99,35%",0%,"0,65%",0%,2025,2,10,0,convocatorias,artistas
48,97,newsletter artistas noviembre 2025,2025-11-04,nuevas convocatorias y programas de acompañami...,248,"1,61%",592,231,"94,67%",54,114,55,"22,54%","31,07%",0%,"98,39%","0,40%","1,21%",0%,2025,11,4,1,convocatorias,artistas
30,75,convocatorias + demo - 5º envío,2025-03-10,nuevas convocatorias,120,"0,83%",447,127,100%,31,128,48,"40,34%",50%,0%,"99,17%",0%,"0,83%",0%,2025,3,10,0,convocatorias,artistas

In [19]:
df.columns = df.columns.str.replace("-", "_")

cols_pct = [
    "non_delivered_rate",
    "trackable_open_rate",
    "click_rate",
    "click_to_open_rate",
    "unsubscription_rate",
    "delivered_rate",
    "hard_bounces_rate",
    "soft_bounces_rate",
    "complaints_rate"
]

for col in cols_pct:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace("%", "")
        .str.replace(",", ".")
        .astype(float)
)

In [20]:
df.to_csv("data_limpia.csv", index=False)